routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('admin/login', 'AdminLoginController@getlogin');
Route::post('admin/login', 'AdminLoginController@postlogin');

Route::get('admin/logout', 'AdminLoginController@logout')->name('admin.logout');


Route::group([ 'prefix' => 'admin', 'middleware' => 'admin' ], function(){

	// admin/users/
	Route::resource('users', 'UserController');

	// admin/categories/
	Route::resource('categories', 'CategoryController', ['except' => 'show']);
	Route::get('categories/{slug}', 'CategoryController@show')->name('categories.show')->where('slug', '[\w\d\-\_]+');

	// admin/topics/
	Route::resource('topics', 'TopicController', ['except' => 'show']);
	Route::get('topics/{slug}', 'TopicController@show')->name('topics.show')->where('slug', '[\w\d\-\_]+');

	// admin/questions/
	Route::resource('questions', 'QuestionController');
	Route::get('/select-ajax/{category_id}', 'AjaxSelectController@selectAjax');

	// admin/answers/
	Route::resource('answers', 'AnswerController', ['only' => 'index']);

});

/*===================================================================================================*/
	Auth::routes();
	
	Route::get('logout', 'HomepageController@logout')->name('logout');

	Route::get('/', 'HomepageController@index');
	Route::get('about', 'HomepageController@about');

	Route::get('contact', 'HomepageController@getcontact');
	Route::post('contact', 'HomepageController@postcontact');
	
	Route::get('profile/{id}', 'HomepageController@getProfile')->name('user.profile');
	Route::post('profile/{id}', 'HomepageController@postProfile')->name('user.update');

	Route::get('category/{id}', 'QuizController@category')->name('category');
	Route::get('topics/{id}', 'QuizController@topic')->name('topic');

	Route::get('question', 'QuizController@correct');
	// OAuth Routes
	Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
	Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

resources/views/admin/layouts/header.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('users.index') }}"> Admin Area - 
                    @if(Auth::check())
                            {{Auth::user()->name}}
                    @endif
                </a>
                
            </div>
            <!-- /.navbar-header -->

              <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                         @if(Auth::check())
                            {{Auth::user()->name}}
                         @endif
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{{ route('users.show', Auth::user()->id) }}"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{{ route('admin.logout') }}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

           @include('admin.layouts.menu')
            <!-- /.navbar-static-side -->
        </nav>

resources/views/admin/layouts/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="">
    <title>Laravel Quiz @yield('title')</title>

    <!-- Khai báo đường dẫn mặc định -->
     <base href="{{asset('')}}">
    <!-- Bootstrap Core CSS -->
    <link href="admin_asset/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

    <!-- MetisMenu CSS -->
    <link href="admin_asset/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="admin_asset/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="admin_asset/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- DataTables CSS -->
    <link href="admin_asset/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="admin_asset/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">

    {{ Html::style('css/styles.css') }}

    @yield('stylesheets')

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        @include('admin.layouts.header')


        <!-- Page Content -->
        @yield('content')
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="admin_asset/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
    

    <!-- Bootstrap Core JavaScript -->
    <script src="admin_asset/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="admin_asset/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="admin_asset/dist/js/sb-admin-2.js"></script>

    <!-- DataTables JavaScript -->
    <script src="admin_asset/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script src="admin_asset/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
    <!-- Tao ndung  -->
    <script type="text/javascript" language="javascript" src="admin_asset/ckeditor/ckeditor.js" ></script>
    @yield('scripts')
</body>

</html>

resources/views/admin/layouts/menu.blade.php
 <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="{{ route('categories.index') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Categories<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('categories.index') }}">List Categories</a>
                                </li>
                                <li>
                                    <a href="{{ route('categories.create') }}">Add Category</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-cube fa-fw"></i> Topics<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('topics.index') }}">List Topics</a>
                                </li>
                                <li>
                                    <a href="{{ route('topics.create') }}">Add Topics</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="glyphicon glyphicon-question-sign"></i> Questions<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('questions.index') }}">List Questions</a>
                                </li>
                                <li>
                                    <a href="{{ route('questions.create') }}">Add Question</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                         <li>
                            <a href="#"><i class="  fa fa-reply-all"></i> Answers<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('answers.index') }}">List Answers</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i> Users<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('users.index') }}">List Users</a>
                                </li>
                                <li>
                                    <a href="{{ route('users.create') }}">Add User</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>

resources/views/admin/layouts/message.blade.php
@if(Session::has('success'))
	<div class="alert alert-success" role="alert">
	 	<strong>Success:</strong> {{Session::get('success')}}
	</div>
@endif


@if(count($errors) > 0)
	<div class=" alert alert-danger" role="alert">
		<strong>Errors:</strong>
		<ul>
			@foreach ($errors->all() as $error)
				<li>
					{{$error}}
				</li>
			@endforeach			
		</ul>
	</div>
@endif