routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('admin/login', 'AdminLoginController@getlogin');
Route::post('admin/login', 'AdminLoginController@postlogin');

Route::get('admin/logout', 'AdminLoginController@logout')->name('admin.logout');


Route::group([ 'prefix' => 'admin', 'middleware' => 'admin' ], function(){

	// admin/users/
	Route::resource('users', 'UserController');

	// admin/categories/
	Route::resource('categories', 'CategoryController', ['except' => 'show']);
	Route::get('categories/{slug}', 'CategoryController@show')->name('categories.show')->where('slug', '[\w\d\-\_]+');

	// admin/topics/
	Route::resource('topics', 'TopicController', ['except' => 'show']);
	Route::get('topics/{slug}', 'TopicController@show')->name('topics.show')->where('slug', '[\w\d\-\_]+');

	// admin/questions/
	Route::resource('questions', 'QuestionController');
	Route::get('/select-ajax/{category_id}', 'AjaxSelectController@selectAjax');

	// admin/answers/
	Route::resource('answers', 'AnswerController', ['only' => 'index']);

});

/*===================================================================================================*/
	Auth::routes();
	
	Route::get('logout', 'HomepageController@logout')->name('logout');

	Route::get('/', 'HomepageController@index');
	Route::get('about', 'HomepageController@about');

	Route::get('contact', 'HomepageController@getcontact');
	Route::post('contact', 'HomepageController@postcontact');
	
	Route::get('profile/{id}', 'HomepageController@getProfile')->name('user.profile');
	Route::post('profile/{id}', 'HomepageController@postProfile')->name('user.update');

	Route::get('category/{id}', 'QuizController@category')->name('category');
	Route::get('topics/{id}', 'QuizController@topic')->name('topic');

	Route::get('question', 'QuizController@correct');
	// OAuth Routes
	Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
	Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Entities\Categories\Category;
use App\Repositories\Categories\CategoryRepository;

class CategoryController extends Controller
{
    protected $categoryRepository;
    public function __construct(CategoryRepository $categoryRepository){
        $this->categoryRepository = $categoryRepository;
    }
    
    public function index()
    {
        $categories = $this->categoryRepository->all();
        return view('admin.categories.index')->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|min:3|max:255',
        ]);
        $data['slug'] = str_slug($request->name, '-');
        $category = $this->categoryRepository->create($data);

        Session::flash('success', 'The category was successfully save!');
        return redirect()->route('categories.show', $category->slug);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $category = $this->categoryRepository->slug('slug', $slug);
        return view('admin.categories.show')->withCategory($category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);
        return view('admin.categories.edit')->withCategory($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name' => 'required|min:3|max:255',
        ]);
        $data['slug'] = str_slug($data['name'], '-');

        $category = $this->categoryRepository->update($data, $id);

        Session::flash('success', 'The category was successfully updated!');
        return redirect()->route('categories.show', $category->slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->categoryRepository->find($id);
        $category->topics()->update(['category_id' => null]);
        $this->categoryRepository->delete($id);

        Session::flash('success', 'The category was successfully deleted!');
        return redirect()->route('categories.index');
    }
}

resources/views/admin/categories/create.blade.php
 @extends('admin.layouts.index')

@section('title', 'Create New Category')
 @section('content')

  <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="page-header">Category
                            <small>Add</small>
                        </h1>
                    </div>
                    <!-- /.col-lg-12 -->
                    <div class="col-md-8 col-md-offset-2" style="padding-bottom:120px">
                        <!-- In error -->
                        @if(count($errors) > 0)
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $err)
                                    {{$err}}<br>
                                @endforeach
                            </div>
                        @endif

                        <form id="form" action="{{ route('categories.store') }}" method="POST"> 
                            <input type="hidden" name="_token" value="{{ csrf_token() }}" />                      
                            <div class="form-group">
                                <label>Category Name</label>
                                <input class="form-control" name="name" placeholder="New category" />
                            </div>                           
                            
                            <div class="row">                                
                                 <div class="col-sm-6">
                                     <input type="submit" value="Create Category" class="btn btn-success btn-block">
                                 </div>

                                 <div class="col-sm-6">
                                     <input type="reset" value="Reset" class="btn btn-default btn-block" id="reset">
                                 </div>
                             </div>
                        <form>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
@endsection 

@section('scripts')
    {!! Html::script('js/reset.js') !!}
@stop        

resources/views/admin/categories/edit.blade.php
 @extends('admin.layouts.index')

@section('title', 'Edit Category')
 @section('content')

  <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="page-header">Category
                            <small>{{$category->name}}</small>
                        </h1>
                    </div>
                    <!-- /.col-lg-12 -->
                    <div class="col-md-8 col-md-offset-2" style="padding-bottom:120px">
                        <!-- In error -->
                        @if(count($errors) > 0)
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $err)
                                    {{$err}}<br>
                                @endforeach
                            </div>
                        @endif

                        {!! Form::model($category, [ 'route' => ['categories.update', $category->id], 'method' => 'PUT' ]) !!}                      
                            <div class="form-group">
                                <label>Category Name</label>
                                <input class="form-control" name="name" placeholder="New category" value="{{$category->name}}" />
                            </div>                           
                            
                            <div class="row">                                
                                 <div class="col-sm-6">
                                     <input type="submit" value="Save Changes" class="btn btn-success btn-block">
                                 </div>

                                <div class="col-sm-6">
                                    <a href="{{route('categories.show', $category->slug)}}" class="btn btn-danger btn-block">Cancel</a>
                                </div>
                             </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
@endsection         

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.index')

@section('title', '| All Categories')

@section('content')

<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Categories
                            <small>List</small>
                        </h1>
                    </div>
                     @if(Session::has('success'))
                            <div class="alert alert-success" role="alert">
                                {{Session::get('success')}}
                            </div>
                        @endif
                    <!-- /.col-lg-12 -->
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr align="center">
                                <th>ID</th>
                                <th>Name</th>
                                <th>Slug</th>
                                <th>View</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- foreach danh sach the loai tu phia controller -->
                            @foreach($categories as $category)
                            <tr class="odd gradeX" align="center">
                                <td>{{$category->id}}</td>
                                <td>{{$category->name}}</td>
                                <td>{{$category->slug}}</td>
                                <td class="center"><i class="glyphicon glyphicon-folder-open"></i><a href="{{ route('categories.show', $category->slug) }}"> View</a></td>
                                <td class="center"><i class="fa fa-pencil fa-fw"></i> <a href="{{ route('categories.edit', $category->id) }}">Edit</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.index')

@section('title', "| $category->name ")

@section('content')

<!-- Page Content -->
      <div id="page-wrapper">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <h1 class="page-header">Detial</h1>
                  </div>
                  <!-- /.col-lg-12 -->
                  <div class="col-md-8 col-md-offset-2" style="padding-bottom:120px">
                      <!-- In error -->
                     @if(Session::has('success'))
                        <div class="alert alert-success" role="alert">
                            <strong>{{Session::get('success')}}</strong> 
                        </div>
                     @endif
                    
                      <div class="form-group">
                          <label>Category Name</label>
                          <input class="form-control" name="name" value="{{$category->name}}" disabled="" />
                      </div> 

                      <div class="form-group">
                          <label>Slug</label>
                          <input class="form-control" name="slug" value="{{$category->slug}}" disabled="" />
                      </div>                                
                      
                      <div class="row">
                        <div class="col-sm-6">
                            <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary btn-block">Edit</a>
                        </div>

                        <div class="col-sm-6">      
                            <a href="#" class="btn btn-danger btn-block" data-toggle="modal" data-target="#delete-{{$category->id}}">Delete</a>
                        </div>

                        <!-- Delete Confirmation Modal (place it right below the button) -->

                            <div class="modal fade" id="delete-{{$category->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            <h4 class="modal-title">Delete Confirmation</h4>
                                        </div>
                                        <div class="modal-body">
                                            <h5>Are you sure you want to delete this category?</h5>
                                        </div>
                                        <div class="modal-footer">
                                            
                                            {!! Form::open(['route' => ['categories.destroy', $category->id], 'method' => 'DELETE', 'style' => 'width: 500px; float:left;']) !!}
                                            <button type="submit" class="btn btn-danger" style="margin-bottom: 5px;">DELETE</button>
                                            {!! Form::close() !!}

                                            <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div> <!--At the end -->

                     </div><br>

                  </div>
              </div>
              <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
      </div>
      <!-- /#page-wrapper -->
@endsection      

   