routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('admin/login', 'AdminLoginController@getlogin');
Route::post('admin/login', 'AdminLoginController@postlogin');

Route::get('admin/logout', 'AdminLoginController@logout')->name('admin.logout');


Route::group([ 'prefix' => 'admin', 'middleware' => 'admin' ], function(){

	// admin/users/
	Route::resource('users', 'UserController');

	// admin/categories/
	Route::resource('categories', 'CategoryController', ['except' => 'show']);
	Route::get('categories/{slug}', 'CategoryController@show')->name('categories.show')->where('slug', '[\w\d\-\_]+');

	// admin/topics/
	Route::resource('topics', 'TopicController', ['except' => 'show']);
	Route::get('topics/{slug}', 'TopicController@show')->name('topics.show')->where('slug', '[\w\d\-\_]+');

	// admin/questions/
	Route::resource('questions', 'QuestionController');
	Route::get('/select-ajax/{category_id}', 'AjaxSelectController@selectAjax');

	// admin/answers/
	Route::resource('answers', 'AnswerController', ['only' => 'index']);

});

/*===================================================================================================*/
	Auth::routes();
	
	Route::get('logout', 'HomepageController@logout')->name('logout');

	Route::get('/', 'HomepageController@index');
	Route::get('about', 'HomepageController@about');

	Route::get('contact', 'HomepageController@getcontact');
	Route::post('contact', 'HomepageController@postcontact');
	
	Route::get('profile/{id}', 'HomepageController@getProfile')->name('user.profile');
	Route::post('profile/{id}', 'HomepageController@postProfile')->name('user.update');

	Route::get('category/{id}', 'QuizController@category')->name('category');
	Route::get('topics/{id}', 'QuizController@topic')->name('topic');

	Route::get('question', 'QuizController@correct');
	// OAuth Routes
	Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
	Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entities\Answers\Answer;
use App\Entities\Questions\Question;
use App\Repositories\Answers\AnswerRepository;

class AnswerController extends Controller
{
    protected $answerRepository;
    public function __construct(AnswerRepository $answerRepository){
        $this->answerRepository = $answerRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $answers = $this->answerRepository->with('question')->get();
        return view('admin.answers.index', ['answers' => $answers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/answers/index.blade.php
@extends('admin.layouts.index')

@section('title', '| All Answers')


@section('content')

<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Answers
                            <small>List</small>
                        </h1>
                    </div>
                    <!-- /.col-lg-12 -->
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr align="center">
                                <th>ID</th>
                                <th>Content</th>
                                <th>Question</th>
                                <th>View</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- foreach danh sach the loai tu phia controller -->
                            @foreach($answers as $answer)
                            <tr class="odd gradeX" align="center">
                                <td>{{$answer->id}}</td>
                                {{-- strip_tags() sẽ loại bỏ các thẻ HTML và PHP ra khỏi chuỗi --}}
                                <td>{{ substr(strip_tags($answer->content), 0, 50) }}{{ strlen(strip_tags($answer->content)) > 50 ? '...': '' }}
                                </td>      
                                <td>{{ substr(strip_tags($answer->question->content), 0, 50) }}{{ strlen(strip_tags($answer->question->content)) > 50 ? '...': '' }}</td>
                               
                                
                                <td class="center"><i class="glyphicon glyphicon-folder-open"></i><a href="{{ route('questions.show', $answer->question->id) }}"> View</a></td>
                                <td class="center"><i class="fa fa-pencil fa-fw"></i> <a href="{{ route('questions.edit', $answer->question->id) }}">Edit</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

@endsection

@section('scripts')

@stop